# project-root/docker/Dockerfile.frontend

FROM node:18-alpine as build

WORKDIR /app

# Copia package.json y package-lock.json
COPY ../../src/frontend/package*.json ./

# Instala dependencias
RUN npm install

# Copia el resto del código
COPY ../../src/frontend/ .

# Compila la app para producción
RUN npm run build

# Etapa para servir
FROM nginx:alpine
COPY --from=build /app/dist /usr/share/nginx/html
EXPOSE 80

CMD ["nginx", "-g", "daemon off;"]
